### ISSUE TITLE
Handle several versions of the SDK generated doc

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit.network#46]
## Problem

Currently, the SDK doc included in the website is the one coming from comit-js-sdk `master` branch.
This is an issue because a developer may purposefully use an older (or released) version of the sdk. In this case, they currently cannot access the SDK doc from the website.

## Goal

Support versioning of documentation on the website. So that the user can select the version of SDK he is viewing.
The version as per the git tags/npm packages.

The aim of this issue is to decide on the website structure to hold several versions and how to select such versions (dropdown, etc). Probably need to generate the doc for a couple of the latest versions of the SDK to validate the look and feel.

Note: Decide to default to `master` or latest release (can be decided in #29).
Note: Do not automate at this stage, automation is handled in #29.

**Comment by yosriady** [comment]
https://v2.docusaurus.io/docs/versioning/

**Comment by tcharding** [comment]
I picked this up, in doing so created a branch `46-versioned-docs` that adds docs to `comit.network/versioned-docs/comit-sdk/` for version 13, 14, and 15 of the `comit-js-sdk`.  Also updates `build.sh` to use `docs/latest/` for importing docs from `js-comit-sdk`.  @yosriady then helped me to start hacking on `generateSidebar.js` but it turns out not to be a trivial thing to do this.

I'm putting this one back in the pipeline for someone more experienced with JS and docasaurus to pick up.
